### ISSUE TITLE
Tracer Filter borders

### ISSUE THREAD

**Issue by sia72abedi** [SideChannelMarvels/Deadpool#16]
I want to know how you calculate your filter borders when you extract the traces. For example:
valgrind --tool=tracergrind --filter=0x08048000-0x08100000 --output=wbDES.trace ./wbDES 12 34 56 78 91 23 45 67
 I want how do you calculate 0x08048000-0x08100000?
I read in one readme of the git repository that these filters chosen to decrease the size of the trace. Is it the only reason?
So I guess you find the block cipher rounds graph(for AES, 10 repetitive figure) without the help of any tool(with eyes) and approximately choose that graph borders as filter address. Am I correct? If I'm not, please explain the procedure of choosing filters.
I try to find the block cipher rounds graph for OpenSSL AES, but it was not possible, because it was a very crowded graph. How can I find the filter borders? please explain generally for every block cipher.

**Comment by doegox** [comment]
Hi
Yes it's only to reduce the amount of data to process, consequently the mem/speed.
On other smaller exemples you'll see we even don't bother about filter and trace all.
Yes I usually select address range by observing the visual representation and finding a repetition (15 or 16 for DES, 9 or 10 for AES128,...).
For the Wyseur challenge, I just looked at the address range of the full binary, see https://github.com/SideChannelMarvels/Deadpool/wiki/Tutorial-%231:-DCA-against-Wyseur-2007-challenge : `objdump -p wbDES |grep -A1 LOAD|grep -B1 "r.x"`
OpenSSL AES is not a whitebox so we won't have such access to large tables. I didn't look to its implementation but it will probably not leak as a whitebox. But you can try...
The easiest is probably just to look for the address range of the function(s) you want to trace.
I hope it gets clearer.
