### ISSUE TITLE
Problem executing scripts

### ISSUE THREAD

**Issue by mercury501** [SideChannelMarvels/Deadpool#6]
Hi, I tried with some examples and writing a little script myself using deadpool_dca.py but every time I run it it outputs this:
`>>> from deadpool_dca import *
>>> T=TracerGrind('whitebox')
>>> T.run(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "deadpool_dca.py", line 300, in run
    oblock=self.get_trace(i, iblock)
  File "deadpool_dca.py", line 460, in get_trace
    output=self._exec(cmd_list, input_stdin)
  File "deadpool_dca.py", line 312, in _exec
    proc = subprocess.Popen(cmd_list, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

I installed tracegrind and it works, i can trace, convert the trace and visualize it with tracegraph but can't seem to make this work.

**Comment by doegox** [comment]
try with './whitebox'
try also to run it once with debug=True in the params (it can't run always in debug mode but at least you get a chance to see the command line it tries to execute)
```T=TracerGrind('./whitebox', debug=True)```

**Comment by LimitedResults** [comment]
My solution, open a shell then type:
sudo cp /usr/bin/valgrind /usr/local/bin/.

then, it works like a charm. 
Very nice tool by the way!
